services:
  mysql:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: employee_db

    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build: ./backend
    ports:
    - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: employee_db

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
    - "8080:80"
    depends_on:
      - backend

volumes:
  mysql-data: